---
- include: install.yml
  tags: ['monit-install']

- include: configure.yml
  tags: ['monit-configure']

- include: services.yml
  tags: ['monit-services']

- name: start monit
  service:
    name: 'monit'
    state: started
    enabled: yes
