---
- include: services/exim4.yml
- include: services/fail2ban.yml

- name: 'set facts'
  set_fact:
    monit_services: '{{ monit_default_services + monit_group_services + monit_host_services }}'

- name: 'Set other facts'
  set_fact:
    active_monit_services: "{{ monit_services | selectattr('name', 'string') | map(attribute='name') | list }}"

- name: 'Get all sevices from file system'
  shell: ls -1 {{ monit_include_dir }} | grep '^monit.*'
  register: defined_monit_services
  changed_when: false
  ignore_errors: true

- name: Remove obsolete monit services
  notify: reload monit
  file:
    path: "{{ monit_include_dir }}/{{ item }}"
    state: absent
  when: "monit_service_delete_unlisted and (item | replace('monit.', '')) not in active_monit_services and (item | replace('monit.', '')) not in ['webinterface', 'mail']"
  with_items: '{{ defined_monit_services.stdout_lines }}'

- name: define monit services
  notify: check and reload monit
  template:
    src: service.j2
    dest: "{{ monit_include_dir }}/monit.{{ item.name }}"
    owner: root
    group: root
  with_items: '{{ monit_services }}'
