---

- name: Ensure /etc/monit exists
  file:
    path: /etc/monit
    state: directory

- name: Generate dhparam.pem if it does not exist
  openssl_dhparam:
    path: /etc/monit/dhparam.pem

- name: Read dhparam
  command: cat /etc/monit/dhparam.pem
  register: monit_ssl_dhparam
  changed_when: false

- name: Generate monit.pem
  no_log: true
  notify: check and restart monit
  template:
    src: 'ssl/certificate.pem'
    dest: '/etc/monit/certificate.pem'
    owner: root
    group: root
    mode: 0700
  when: monit_ssl_certificate != '' and monit_ssl_certificate_key != ''
