---
- name: start monit
  service:
    name: 'monit'
    state: started
    enabled: yes

- name: restart monit
  service:
    name: 'monit'
    state: restarted
    enabled: yes

- name: reload monit
  service:
    name: 'monit'
    state: restarted
    enabled: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload initctl
  command: initctl reload-configuration

- name: check and restart monit
  shell: "monit -t | grep 'Control file syntax OK'"
  notify: restart monit

- name: check and reload monit
  shell: "monit -t | grep 'Control file syntax OK'"
  notify: reload monit
