---
- name: Check if automysqlbackup is installed
  register: _monit_check_automysqlbackup
  command: automysqlbackup -h
  ignore_errors: true
  changed_when: false

- name: 'Add automysqlbackup to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_automysqlbackup }}'
  when: _monit_check_automysqlbackup.rc == 0
