---
- name: Check if backup is installed
  register: _monit_check_backup
  command: test -e /usr/local/sbin/duptools
  ignore_errors: true
  changed_when: false

- name: 'Add backup to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_backup }}'
  when: _monit_check_backup.rc == 0
