---
- name: Check if exim is installed
  register: _monit_check_exim
  shell: exim --version
  ignore_errors: true
  changed_when: false

- set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_exim4 }}'
  when: _monit_check_exim.rc == 0
