---
- name: Check if dovecot is installed
  register: _monit_check_dovecot
  command: fdisk -l /dev/sdb5 | grep Disk
  ignore_errors: true
  changed_when: false

- name: 'Add dovecot to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_dovecot }}'
  when: _monit_check_dovecot.rc == 0



check filesystem disk1 with path /dev/sda1
    if read rate > 1 MB/s for 5 cycles then alert
    if read rate > 500 operations/s for 5 cycles then alert
    if write rate > 1 MB/s for 5 cycles then alert
    if write rate > 500 operations/s for 5 cycles then alert
    # Service Time is the time taken to complete a read or a write operation
    if service time > 100 milliseconds for 5 cycles then alert