---
- name: Check if firewall is installed
  register: _monit_check_firewall
  command: test -e /usr/local/bin/firewall.sh
  ignore_errors: true
  changed_when: false

- name: 'Add firewall to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_firewall }}'
  when: _monit_check_firewall.rc == 0
