---
- name: Check if mysql is installed
  register: _monit_check_mysql
  command: mysql -V | grep -o MariaDB
  ignore_errors: true
  changed_when: false

- name: 'Add mysql to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_mariadb }}'
  when: _monit_check_mysql.rc == 0
