---
- name: Check if nginx is installed
  register: _monit_check_nginx
  command: nginx -v
  ignore_errors: true
  changed_when: false

- name: 'Add nginx to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_nginx }}'
  when: _monit_check_nginx.rc == 0
