---
- name: Check if php7.0-fpm is installed
  register: _monit_check_php70_fpm
  command: php-fpm7.0 -v
  ignore_errors: true
  changed_when: false

- name: 'Add php7.0-fpm to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_php70_fpm }}'
  when: _monit_check_php70_fpm.rc == 0
