---
- name: Check if redis-server is installed
  register: _monit_check_redis_server
  command: redis-server --version
  ignore_errors: true
  changed_when: false

- name: 'Add redis-server to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_redis_server }}'
  when: _monit_check_redis_server.rc == 0
