---
- name: Check if softraid is installed
  register: _monit_check_softraid
  command: grep raid /proc/mdstat
  ignore_errors: true
  changed_when: false

- name: 'Add softraid to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_softraid }}'
  when: _monit_check_softraid.rc == 0
