---
- name: Check if sslcertcheck is installed
  register: _monit_check_sslcertcheck
  command: test -e /usr/local/bin/sslcertcheck.sh
  ignore_errors: true
  changed_when: false

- name: 'Add sslcertcheck to monit_default_services fact'
  set_fact:
    monit_default_services: '{{ monit_default_services + monit_service_sslcertcheck }}'
  when: _monit_check_sslcertcheck.rc == 0
